interface ComparatorObject {
    argName: string;
    operator: "EQUAL" | "NOT_EQUAL" | "GREATER_THAN" | "GREATER_THAN_OR_EQUAL" | "LESS_THAN" | "LESS_THAN_OR_EQUAL" | "IS_NULL" | "IS_NOT_NULL" | "LIKE" | "IN" | "NOT_IN";
    columnName: string;
    modifier?:
        | "STR:ASCII"
        | "STR:CHAR_LENGTH"
        | "STR:LENGTH"
        | "STR:LOWER"
        | "STR:LTRIM"
        | "STR:REVERSE"
        | "STR:RTRIM"
        | "STR:TRIM"
        | "STR:UPPER"
        | "NUM:ABS"
        | "NUM:ACOS"
        | "NUM:ASIN"
        | "NUM:ATAN"
        | "NUM:CEIL"
        | "NUM:COS"
        | "NUM:COT"
        | "NUM:DEGREES"
        | "NUM:EXP"
        | "NUM:FLOOR"
        | "NUM:LN"
        | "NUM:LOG"
        | "NUM:LOG10"
        | "NUM:LOG2"
        | "NUM:RADIANS"
        | "NUM:SIGN"
        | "NUM:SIN"
        | "NUM:SQRT"
        | "NUM:TAN"
        | "DATE:DATE"
        | "DATE:DAY"
        | "DATE:DAYNAME"
        | "DATE:DAYOFMONTH"
        | "DATE:DAYOFWEEK"
        | "DATE:DAYOFYEAR"
        | "DATE:HOUR"
        | "DATE:LAST_DAY"
        | "DATE:MICROSECOND"
        | "DATE:MINUTE"
        | "DATE:MONTH"
        | "DATE:MONTHNAME"
        | "DATE:QUARTER"
        | "DATE:SECOND"
        | "DATE:SEC_TO_TIME"
        | "DATE:TIME"
        | "DATE:TIME_TO_SEC"
        | "DATE:TO_DAYS"
        | "DATE:WEEK"
        | "DATE:WEEKDAY"
        | "DATE:WEEKOFYEAR"
        | "DATE:YEAR"
        | "DATE:YEARWEEK"
        | "ADV:BIN";
}

export default ComparatorObject;
